# Generated by Django 5.1.3 on 2025-03-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_lecturer_student_course_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
